apiVersion: v1
kind: Service
metadata:
  name: receiver
  labels:
    app: receiver
  namespace: monitoring
spec:
  selector:
    qcloud-app: receiver
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

