{
 "title": "Namespace维度",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created,namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "容器 CPU 使用",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$namespace\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "容器内存使用",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"$namespace\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  {
   "title": "ReplicaController",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RelicaSet数量",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_replicaset_created{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "endpoint数量",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kube_endpoint_created{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "endpoint address available",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_endpoint_address_available{namespace=~\"$namespace\"})by(endpoint)",
       "legendFormat": "endpoint={{endpoint}}"
      }
     ]
    },
    {
     "title": "endpoint not ready",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_endpoint_address_not_ready)by(endpoint)",
       "legendFormat": "endpoint={{endpoint}}"
      }
     ]
    }
   ]
  }
 ]
}