{
 "title": "主机监控",
 "time": { "from": "2018-06-18T00:50:08.978Z", "to": "2018-06-19T08:50:22.144Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_node_created, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "node运行时长",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU 使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"node-exporter\",mode!=\"idle\", instance=~\"$node\"}[5m])) without (cpu, mode)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU load 5min",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(node_load5)by(node)" }
   ]
  },
  { "title": "内存", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job='node-exporter',instance=~\"$node\"} - node_memory_MemFree_bytes{job='node-exporter',instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\"}+node_memory_Slab_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "磁盘", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "磁盘使用情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_filesystem_free_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev|none|devpts|sysfs|debugfs|fuse.*\", instance=~\"$node\"} / node_filesystem_size_bytes{fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|udev|none|devpts|sysfs|debugfs|fuse.*\", instance=~\"$node\"} * 100",
     "legendFormat": "device:{{device}} instance:{{instance}}"
    }
   ]
  },
  {
   "title": "使用I/O的毫秒数（5分钟内）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{instance=~'$node'}[5m])) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "网络", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "网络出入带宽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node-exporter\",device=\"eth0\"}[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "- irate(node_network_transmit_bytes_total{job=\"node-exporter\",device=\"eth0\"}[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "网络出入流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job=\"node-exporter\",device=\"eth0\"}",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "node_network_transmit_bytes_total{job=\"node-exporter\",device=\"eth0\"}",
     "legendFormat": "{{instance}}-out"
    }
   ]
  },
  {
   "title": "网络出入带宽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"node-exporter\",device=\"eth0\"}[5m])",
     "legendFormat": "{{instance}}-in"
    },
    {
     "expr": "- irate(node_network_transmit_packets_total{job=\"node-exporter\",device=\"eth0\"}[5m])",
     "legendFormat": "{{instance}}-out"
    }
   ]
  }
 ]
}