{
 "title": "Cluster概览",
 "description": "Summary metrics about containers running on Kubernetes nodes.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(container_cpu_system_seconds_total,instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_cpu_system_seconds_total, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health Meter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node $node Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"}) / sum(kube_node_status_allocatable_pods{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node $node CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\", instance_name=~\"$node\"}[1m]))/ sum(rate(node_cpu_seconds_total{instance_name=~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Node $node GPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(dcgm_gpu_utilization{instance_name=~\"$node\"})/100"
    }
   ]
  },
  {
   "title": "Node $node Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes{instance_name=~\"$node\"})) - (sum(node_memory_MemAvailable_bytes{instance_name=~\"$node\"}))) / sum(node_memory_MemTotal_bytes{instance_name=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node $node Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job='node-exporter', instance_name=\"$node\", device=~\".*dev.*\", device!~\".*docker.*\", mountpoint!=\"/etc/resolv.conf\",}) - sum(node_filesystem_free_bytes{job='node-exporter', instance_name=\"$node\", device=~\".*dev.*\", device!~\".*docker.*\", mountpoint!=\"/etc/resolv.conf\",})) / sum(node_filesystem_free_bytes{job='node-exporter', instance_name=\"$node\", device=~\".*dev.*\", device!~\".*docker.*\", mountpoint!=\"/etc/resolv.conf\",})"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node $node Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Node $node CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores{node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"$node\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$node\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Node $node GPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(dcgm_gpu_utilization{instance_name=~\"$node\"})",
     "legendFormat": "gpu utilization"
    }
   ]
  },
  {
   "title": "Node $node Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job='node-exporter', instance_name=\"$node\", device=~\".*dev.*\", device!~\".*docker.*\", mountpoint!=\"/etc/resolv.conf\"}) - sum(node_filesystem_free_bytes{job='node-exporter', instance_name=\"$node\", device=~\".*dev.*\", device!~\".*docker.*\", mountpoint!=\"/etc/resolv.conf\"}))/1024/1024/1024",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job='node-exporter', instance_name=\"$node\", device=~\".*dev.*\", device!~\".*docker.*\", mountpoint!=\"/etc/resolv.conf\"})/1024/1024/1024",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Node $node Disk IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate(node_disk_read_bytes_total{job=\"node-exporter\", instance_name=~\"$node\"}[1m]))",
     "legendFormat": "io-read"
    },
    {
     "expr": "sum (irate(node_disk_written_bytes_total{job=\"node-exporter\", instance_name=~\"$node\"}[1m]))",
     "legendFormat": "io-write"
    }
   ]
  },
  {
   "title": "Node $node Network IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg by (instance_name)(rate(node_network_receive_bytes_total{job=\"node-exporter\",instance_name=~\"$node\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{instance_name}}-receive"
    },
    {
     "expr": "avg by (instance_name)(rate(node_network_transmit_bytes_total{job=\"node-exporter\",instance_name=~\"$node\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{instance_name}}-send"
    }
   ]
  },
  {
   "title": "Node $node Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance_name=~\"$node\"})/1024/1024/1024",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance_name=~\"$node\"})/1024/1024/1024",
     "legendFormat": "capacity"
    },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{instance_name=~\"$node\"})-sum(node_memory_MemAvailable_bytes{instance_name=~\"$node\"}))/1024/1024/1024",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Cluster Total Tasks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "tasks" }
   ],
   "targets": [
    {
     "expr": "sum(count(kube_pod_labels{job=\"kube-state-metrics\", label_app!=\"\", label_app=~\".*tensorflow.*|.*spark.*\"}) by (label_app))",
     "legendFormat": "Running Tasks"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Containers Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Waiting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Terminated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=\"kube-system\"}[30m]))"
    }
   ]
  },
  {
   "title": "CPU Cores Requested by Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Memory Requested By Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 41 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   ]
  }
 ]
}