{
 "title": "Pod 监控",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_created, pod)"
   }
  ]
 },
 "panels": [
  { "title": "CPU&内存（所有Pod）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "容器 CPU 使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", pod_name=~\"$pod\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "容器内存使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", pod_name=~\"$pod\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "网络（所有Pod）", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "网络出入带宽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}-in"
    },
    {
     "expr": "- irate(container_network_transmit_bytes_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}-out"
    }
   ]
  },
  {
   "title": "网络出入流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}-in"
    },
    {
     "expr": "- container_network_transmit_bytes_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}",
     "legendFormat": "{{pod_name}}-out"
    }
   ]
  },
  {
   "title": "网络出入收发包",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}-in"
    },
    {
     "expr": "- irate(container_network_transmit_packets_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}-out"
    }
   ]
  },
  { "title": "磁盘(所有Pod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "磁盘读取速度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}-read"
    }
   ]
  },
  {
   "title": "磁盘写入速度",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{job=\"node-cadvisor\", pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{pod_name}}-write"
    }
   ]
  },
  { "title": "Pod异常监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "长时间异常状态（超过5分钟）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kube_pod_status_phase{pod=~\"$pod\", phase!~\"Running|Succeeded\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}